### ISSUE TITLE
Ionchódú na gcarachtar sa cholún QueryTerms

### ISSUE THREAD

**Issue by rodoch** [gaois/Gaois.QueryLogger#3]
Bíonn carachtair áirithe a bhfuil síneadh fada nó a leithéid orthu sa cholún QueryTerms truaillithe:

![pic](https://user-images.githubusercontent.com/5305694/57140930-e7138a80-6db0-11e9-9df8-0352073ac167.png)

Féach nach dtarlaíonn sé seo i gcónaí (tá 'représentants' agus 'tríthoiseacha' ceart sa sampla thuas, ní ionann agus 'ríomh-atreorú'). Tá ionchódú Latin1_General_CI_AS ar an cholún in SQL Server agus níor cheart, mar sin, gur fadhb é seo a bhaineann leis an bhunachar.

**Comment by rodoch** [comment]
Éiríonn sé seo níos spéisiúla @oraghalb ...

An fhadhb anseo ná go bhfuil carachtair ASCII nó eile (rud ar bith seachas UTF-8) á n-úsáid sa bhunchuardach atá á dhéanamh ar an suíomh agus ní hé go bhfuiltear á dtruailliú níos déanaí. Lean an nasc thíos ar cóip é de cheann de na cuardaigh a rinneadh ar an suíomh a raibh QueryTerms truaillithe mar thoradh air (d'úsáid mé an méid atá sa cholún QueryText leis seo a athchruthú):

[https://www.tearma.ie/q/r%C3%83%C2%A1dalaigh/ga/](https://www.tearma.ie/q/r%C3%83%C2%A1dalaigh/ga/)

Féach go raibh an carachtar ASCII ann i gcónaí agus nach ndearnadh truailliú air níos déanaí agus an t-iarratas á logáil:

![pic](https://user-images.githubusercontent.com/5305694/57149503-bee15700-6dc3-11e9-9d36-a680648c67bb.png)

Chuir sé seo iontas orm ar bhealach amháin ach, ar an láimh eile, míníonn sé cén fáth a raibh formhór na dtéarmaí a raibh carachtair speisialta iontu á logáil gan fhadhb (féach an bun-isiú thuas). Ansin, d'fhiosraigh mé foinse na gcuardach seo ina bhfuil ionchódú truaillithe agus cé eile lena mbaineann siad ach... Bingbot! (Ní miste liom an seoladh IP a roinnt thíos ós rud é gur eolas poiblí atá ann.)

![pic](https://user-images.githubusercontent.com/5305694/57149896-b4738d00-6dc4-11e9-9f17-8ea0655b728a.png)

![pic](https://user-images.githubusercontent.com/5305694/57149927-c0f7e580-6dc4-11e9-92a6-3fcada8b8a7a.png)

Más ea, ní fadhb dár ndéantús féin é seo. Níl mé cinnte an fiú nó féidir é a réiteach ach oiread - más i bhfoirm truaillithe a tháinig an t-iarratas chugainn seans maith go bhfuil an t-eolas a bheadh riachtanach leis na carachtair a dhíchódú caillte. Aon taithí agat @michmech leis seo? (Seans gur cheart dom an freagra a lorg sa leabhar agat).

**Comment by rodoch** [comment]
Agus is cosúil go bhfuil aitheantas éigin ag an fhadhb seo in áit eile: [https://stackoverflow.com/questions/25031946/bingbot-converts-unicode-characters-to-not-understandable-symbols](https://stackoverflow.com/questions/25031946/bingbot-converts-unicode-characters-to-not-understandable-symbols)

**Comment by rodoch** [comment]
Tar éis breis machnaimh a dhéanamh ar an cheist seo tá mé sásta leis an mhíniú atá tugtha thuas agus is soiléir nach ceist é seo a bhaineann le Gaois.QueryLogger; tá an bogearra ag feidhmiú faoi mar is ceart tríd síos sa phróiseas. Mar sin, tá [ceist nua](https://github.com/gaois/Tearma/issues/27) oscailte agam ar stórlann Téarma (an áit a dtagann an fhadhb seo i gceist) agus molaim an cheist anseo a dhruideadh - ceart go leor @oraghalb?

**Comment by oraghalb** [comment]
Ceart go leor liomsa.
